name: eiin_manager
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^7.1.1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.0+2
  provider: ^4.3.2+2
  pagination: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

